[package]
name = "dodb-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dodb-core = { path = "../dodb-core" }
dodb-protocol = { path = "../dodb-protocol" }
dodb-service = { path = "../dodb-service" }
quinn.workspace = true
rustls-pemfile.workspace = true
tokio.workspace = true
