[package]
name = "dodb-bench"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dodb-client = { path = "../dodb-client" }
dodb-core = { path = "../dodb-core" }
dodb-protocol = { path = "../dodb-protocol" }
dodb-server = { path = "../dodb-server" }
dodb-service = { path = "../dodb-service" }
dodb-storage = { path = "../dodb-storage" }
rcgen.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
